name: Test envolved

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unittest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"] # format: 3.7, 3.8, 3.9
        platform: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install PIP
      run: |
        python -m pip install --upgrade pip
    - name: Install dependencies
      run: |
        sh scripts/install.sh
    - name: Lint
      run: |
        poetry run sh scripts/lint.sh
    - name: Tests
      run: |
        poetry run sh scripts/coverage.sh